config/routes.rb
Rails.application.routes.draw do
  get 'page/navigate'
  get 'page/about'
  get 'page/profile'
  get 'page/contact'
  get 'page/rides'
  get 'page/home'
  get 'page/services'

  root 'page#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def navigate
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AgileDev</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta charset="utf-8">
</head>
<body>



<%= render 'shared/header' %>

<%= render 'shared/main_navigation' %>




<%= yield %>
<%= render 'shared/footer_navigation' %>



</body>
</html>

app/views/page/about.html.erb
<div class="wrapper">
  <div class="row content-wrapper">
    <div class="columns large-12">
      <div class="row">
        <div class="columns large-8 content">
          <h1 class="page-title">About Us</h1>
          <div>
            <h2 class="sub-title">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis</h2>
          </div>

          <ul class="row">
            <li class="columns large-4">
              <div class="img-wrapper">
                <%= image_tag("house.jpg", alt:"Ez", class:"th about-image")%>
              </div>
              <h3 class="employer-name">Ez Layata</h3>
              <p>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat porro voluptatem</p>
            </li>
            <li class="columns large-4">
              <div class="img-wrapper">
                <%= image_tag("slide3.jpg", alt:"Nate", class:"th about-image")%>
              </div>
              <h3 class="employer-name">Nathan</h3>
              <p>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat volupt porro atem</p>
            </li>
            <li class="columns large-4">
              <div class="img-wrapper">

                <%= image_tag("slide1.jpg", alt:"Terry", class:"th about-image")%>
              </div>
              <h3 class="employer-name">Terry</h3>
              <p>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat porro voluptatem</p>
            </li>
          </ul>

          <ul class="row">
            <li class="columns large-4">
                <div class="img-wrapper">

                <%= image_tag("logo.png", alt:"", class:"th about-image")%>
              </div>
              <h3 class="employer-name">Shelly</h3>
              <p>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat porro voluptatem</p>
            </li>
            <li class="columns large-4">
              <div class="img-wrapper">
                <%= image_tag("logo.png", alt:"", class:"th about-image")%>
              </div>
              <h3 class="employer-name">Dylan</h3>
              <p>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat volupt porro atem</p>
            </li>

          </ul>
        </div>
        <div class="columns sidebar large-4 ">
          <h1 class="page-title">Our Acheivements</h1>
          <ul>
            <li><a href="#">dolorem ipsum quia dolor sit amet</a></li>
            <li><a href="#">sed quia non numquam eius modi tempora </a></li>
            <li><a href="#">dolorem ipsum quia dolor sit amet</a></li>
            <li><a href="#">sed quia non numquam eius modi tempora </a></li>
            <li><a href="#">dolorem ipsum quia dolor sit amet</a></li>
            <li><a href="#">sed quia non numquam eius modi tempora </a></li>
            <li><a href="#">dolorem ipsum quia dolor sit amet</a></li>
            <li><a href="#">sed quia non numquam eius modi tempora </a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/page/contact.html.erb
<div class="wrapper">
  <div class="row content-wrapper">
    <div class="columns large-12">
      <div class="row">
        <div class="columns large-12 content ">
          <h1 class="page-title">Contact Us</h1>
          <div>
            <h2 class="sub-title">At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt</h2>
          </div>
          <div class="row contact-form">
            <div class="columns large-8">
              <form id="contact-form" method="post" action="#">
                <input type="text" name="name" placeholder="Name:">
                <input type="text" name="email" placeholder="Email:">
                <input type="text" name="subject" placeholder="Subject:">
                <textarea  name="message"></textarea>
                <input type="submit" class="button" name="submit" value="send">
              </form>
            </div>
            <div class="columns large-4">
              <div id="map_canvas"></div>
              <ul class="vcard">
                <li class="fn">FANTASTIC 5</li>
                <li class="street-address">255, Willson Street,Caulfield</li>
                <li class="locality">Melbourne</li>
                <li><span class="state">Victoria</span>, <span class="zip">122211</span></li>
                <li class="email"><span>Email:</span>email@domain.com</li>
                <li class="telephone"><span>Tel:</span>(122)3456789, (121)3456079, (121)2341234</li>
                <li class="fax"><span>Tel:</span>1800-726-192</li>
              </ul>
            </div>
          </div>
        </div>
        <div class="row collapse">
          <div class="columns large-12"> </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/page/home.html.erb
<div class="wrapper">
    <div class="tagline-row">
      <div class="row tagline">
        <div class="columns large-12">
          <h2 class="center">
            Tincidunt. ac urna urna facilisis etiam platea ac phasellus vut
            pulvinar dolor porta augue montes odio dapibus elementum augue ultricies quis.</h2>
        </div>
      </div>
    </div>
    <div class="service-box">
      <div class="row service">
        <div class="columns large-4">
          <div class="box">
            <p> <%= image_tag("threeup3.jpg", alt:"") %></p>
            <h1>Lorem ipsum sit dolor esm</h1>
            <p>cum magna diam Duis amagna augue natoque odion nisi sed magna nascetur turpis inet sed parturient cum velit lacus Magna facilisis et cursus montes Turpisinet magnis parturient turpis magna turpis habitasse integ ultricies odion adipiscing eros nisi nunc aliquet lorem ipsum sites dolor esme turpis magna augue odio nisi phasellus pulvinar </p>
          </div>
        </div>
        <div class="columns large-4">
          <div class="box">
            <p> <%= image_tag("threeup3.jpg", alt:"") %></p>
            <h1>Phasell pulvinar magna</h1>
            <p>cum magna diam Duis amagna augue natoque odion nisi sed magna nascetur turpis inet sed parturient cum velit lacus Magna facilisis et cursus montes Turpisinet magnis parturient turpis magna turpis habitasse integ ultricies odion adipiscing eros nisi nunc aliquet lorem ipsum sites dolor esme turpis magna augue odio nisi phasellus pulvinar </p>
          </div>
        </div>
        <div class="columns large-4">
          <div class="box">
            <p> <%= image_tag("threeup3.jpg", alt:"") %></p>
            <h1>Lorem ipsum sit dolor esm</h1>
            <p>cum magna diam Duis amagna augue natoque odion nisi sed magna nascetur turpis inet sed parturient cum velit lacus Magna facilisis et cursus montes Turpisinet magnis parturient turpis magna turpis habitasse integ ultricies odion adipiscing eros nisi nunc aliquet lorem ipsum sites dolor esme turpis magna augue odio nisi phasellus pulvinar </p>
          </div>
        </div>
      </div>
    </div>
    <div class="testimonial-row">
      <div class="row">
        <div class="columns large-11">
          <div class="testimonial flexcar">
            <ul class="slides">
              <li>
                <p>Tincidunt. Ac urna urna facilisis etiam platea ac, phasellus, vut pulvinar? Dolor! Porta augue. Montes odio dapibus Elementum augue ultricies quis ridiculus aliquam vut, dis nunc diam! Arcu aliquet odio in. Eu sed et mauris tincidunt. Ultricies. Massa egestas, odio et arcu egestas egestas integer, urna cras nunc egestas, lorem no Facilisis enim cum nascetur placerat magna magna cursus natoque velit porttitor turpis rcu ac vel natoque enim dictumst urna phasellus tincidunt aliquet Tincidunt urna urna facilisis etiam platea ac, phasellus, vut pulvinar? Dolor! Porta augue. Montes odio dapibus? Elementum augue ultricies quis. Ac ridiculus, aliquam,</p>
              </li>
              <li>
                <p>cum magna diam Duis amagna augue natoque odion nisi sed magna nascetur turpis inet sed parturient cum velit lacus Magna facilisis et cursus montes Turpisinet magnis parturient turpis magna turpis habitasse integ ultricies odion adipiscing eros nisi nunc aliquet lorem ipsum sites dolor esme </p>
              </li>
              <li>
                <p>Massa egestas, odio et arcu egestas egestas integer, urna cras nunc egestas cum magna diam Duis amagna augue natoque odion nisi sed magna nascetur turpis inet sed parturient cum velit lacus Magna facilisis et cursus montes Turpisinet magnis parturient turpis magna turpis habitasse integ ultricies odion adipiscing eros nisi nunc aliquet lorem ipsum sites dolor esme </p>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>


  </div>

app/views/page/profile.html.erb
<div class="wrapper">

  <div class="header">

  <h1>Page#profile</h1>
  <p>Find me in app/views/page/Profile.html.erb</p>

</div>
</div>

app/views/page/rides.html.erb
<div class="wrapper">
  <div class="row content-wrapper">
    <div class="columns large-12">
      <div class="row">
        <div class="columns large-8 content">
          <h1 class="page-title">Blog Posts</h1>
          <p><b>Egestas aliquam vel ultrices integer</b>, ut sit pellentesque, et montes, turpis phasellus mauris porta <a href="#">parturient</a> platea pulvinar risus, lectus? Pid! Elementum sociis nunc sit! Dolor in eu ut placerat pellentesque, platea est risus etiam, dolor! Nec, penatibus odio scelerisque elementum pulvinar urna, dis nec vel nunc ut mid! In eros magna vel urna a platea proin, in tortor ultricies, et egestas amet, pellentesque ac, sit est ac integer ut cum porttitor penatibus, sed purus odio! Mauris nec? Quis, facilisis, tempor magna in vel lacus, cras risus, vel montes penatibus ultrices, aenean penatibus, nec lectus lacus penatibus? Egestas duis. Diam phasellus, integer in etiam sociis porta turpis proin in? Ridiculus! Turpis mauris placerat. Tincidunt in scelerisque diam mus egestas? Augue mauris. Augue etiam. Porta? Cum sed platea, nunc elit ultricies phasellus auctor augue aliquam tempor. Amet velit, adipiscing sed ac dictumst penatibus aliquam, parturient, purus. Enim nec augue mauris elementum cras.</p>
          <p>Dolor amet amet lectus phasellus, dolor aliquam. Nascetur arcu urna placerat, mid, elit adipiscing parturient nec ac dolor amet. Velit? Augue enim nisi phasellus velit, sit nunc elit natoque lacus, mus et ac vut mattis? Eu pulvinar pulvinar et, in habitasse, lundium, ridiculus? Arcu, ultrices, amet augue, ac pulvinar urna cum, turpis pid, eu. Ac porttitor, ut aliquam in? Ridiculus ac. Urna augue pid tortor porttitor vut, amet, enim ut turpis, sociis dignissim, augue sit porta scelerisque, in lectus aliquam vut habitasse ac? Rhoncus, placerat! Eros nec tincidunt ultrices scelerisque lorem. Sed diam mauris diam egestas? Amet in, mauris, nunc sociis scelerisque, sed eu, et mus, pulvinar, velit et facilisis lacus a aliquam non ut, sit porta? Diam ultricies? Placerat ut auctor urna adipiscing sit, quis rhoncus pulvinar integer sed proin? Porta penatibus magna, elementum, lorem nisi, elit adipiscing, mauris, porta egestas pid, vut sed arcu tristique, rhoncus sit.</p>
        </div>
        <div class="columns large-4 content sidebar">
          <h1 class="page-title services">Our Services</h1>
          <ul>
            <li class="bullet"><a href="#">Purus magnis augue adipiscing mid magna</a></li>
            <li class="bullet"><a href="#">Amet dignissim natoque, dignissim lacus</a></li>
            <li class="bullet"><a href="#">Purus magnis augue adipiscing mid magna</a></li>
            <li class="bullet"><a href="#">Amet dignissim natoque, dignissim lacus</a></li>
            <li class="bullet"><a href="#">Purus magnis augue adipiscing mid magna</a></li>
            <li class="bullet"><a href="#">Amet dignissim natoque, dignissim lacus</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/page/services.html.erb
<div class="wrapper">

  <div class="row content-wrapper">
    <div class="columns large-12">
      <div class="row">
        <div class="columns large-4 content sidebar">
          <h1 class="page-title services">Why Choose us</h1>
          <ul>
            <li class="bullet"><a href="#">Purus magnis augue adipiscing mid magna</a></li>
            <li class="bullet"><a href="#">Amet dignissim natoque, dignissim lacus</a></li>
            <li class="bullet"><a href="#">Purus magnis augue adipiscing mid magna</a></li>
            <li class="bullet"><a href="#">Amet dignissim natoque, dignissim lacus</a></li>
            <li class="bullet"><a href="#">Purus magnis augue adipiscing mid magna</a></li>
            <li class="bullet"><a href="#">Amet dignissim natoque, dignissim lacus</a></li>
            <li class="bullet"><a href="#">Purus magnis augue adipiscing mid magna</a></li>
            <li class="bullet"><a href="#">Amet dignissim natoque, dignissim lacus</a></li>
            <li class="bullet"><a href="#">Purus magnis augue adipiscing mid magna</a></li>
            <li class="bullet"><a href="#">Amet dignissim natoque, dignissim lacus</a></li>
            <li class="bullet"><a href="#">Purus magnis augue adipiscing mid magna</a></li>
            <li class="bullet"><a href="#">Amet dignissim natoque, dignissim lacus</a></li>
          </ul>
        </div>
        <div class="columns large-8">
          <h1 class="page-title">Our Services</h1>
          <div class="row">
            <div class="columns large-6">
              <div class="service-box-page">
                <p> <%= image_tag("logo.png", alt:"") %></p>
                <h4>Service Title</h4>
                <p>Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet</p>
              </div>
            </div>
            <div class="columns large-6">
              <div class="service-box-page">
                <p> <%= image_tag("logo.png", alt:"") %></p>
                <h4>Service Title</h4>
                <p>Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet</p>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="columns large-6">
              <div class="service-box-page">
                <p> <%= image_tag("logo.png", alt:"") %></p>
                <h4>Service Title</h4>
                <p>Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet</p>
              </div>
            </div>
            <div class="columns large-6">
              <div class="service-box-page">
                <p> <%= image_tag("logo.png", alt:"") %></p>

                <h4>Service Title</h4>
                <p>Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>


</div>
</div>
<script src="js/jquery.min.js"></script>
<script src="js/hoverIntent.js"></script>
<script src="js/superfish.js"></script>
<script>
    Modernizr.load({
        test: Modernizr.placeholder,
        nope: 'js/placeholder.min.js'
    });

    function goToNewPage() {
        if (document.getElementById('target').value) {
            window.location.href = document.getElementById('target').value;
        }
    }
</script>
<script>
    $(document).ready(function () {
        $('ul.sf-menu').superfish({
            animation: {
                height: 'show'
            },
            delay: 400
        });
        $("img.scrollToTop").click(function () {
            $("html, body").animate({
                scrollTop: 0
            }, "slow");
        });
    });
</script>
</body>

app/views/shared/_footer_navigation.html.erb
<div class="wrapper">
  <div class="header">
<footer class="footer">
  <div class="row">
    <div class="columns large-12 footer-inner">
      <div class="row">
        <div class="columns large-3 box">
          <div class="">
            <h2 class="footer-title">Resources</h2>
            <ul>
              <li><a href="index.html">home</a></li>
              <li><a href="gallery.html">gallery</a></li>
              <li><a href="#">faqs</a></li>
              <li><a href="contact.html">contact us</a></li>
              <li><a href="#">testimonials</a></li>
              <li><a href="blog.html">blog</a></li>
            </ul>
          </div>
        </div>
        <div class="columns large-3 box">
          <div>
            <h2 class="footer-title">links </h2>
            <ul>
              <li><a href="index.html">home</a></li>
              <li><a href="gallery.html">gallery</a></li>
              <li><a href="#">faqs</a></li>
              <li><a href="contact.html">contact us</a></li>
              <li><a href="#">testimonials</a></li>
              <li><a href="blog.html">blog</a></li>
            </ul>
          </div>
        </div>
        <div class="columns large-3 box">
          <div>
            <h2 class="footer-title">follow us</h2>
            <ul>
              <li><a href="#" class="media tweeter"></a>Follow us on twitter</li>
              <li><a href="#" class="media youtube"></a>Follow us on youtube</li>
              <li><a href="#" class="media facebook"></a>Follow us on facebook</li>
              <li><a href="#" class="media gmail"></a>Follow us on google plus</li>
            </ul>
          </div>
        </div>
        <div class="columns large-3 box">
          <div>
            <h2 class="footer-title">Contact us</h2>
            <p>255, Willson Street,Caulfield, 122211, Melbourne</p>
            <p><b>Tel:</b> (122)3456789, (121)3456079, (121)2341234</p>
            <p><b>Fax:</b> (121)5647289, (122)34526589</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

  </div>
</div>

app/views/shared/_header.html.erb
<head>
  <title>DreamzBank</title>
  <meta charset="utf-8">
  <link rel="stylesheet" href="stylesheets/foundation.min.css">
  <link rel="stylesheet" href="stylesheets/superfish.css">
  <link rel="stylesheet" href="stylesheets/stylesheet.css">
  <link rel="stylesheet" href="javascripts/slider/flexslider.css">
  <link rel="stylesheet" href="js/slider/flexcar.css">
  <link href='http://fonts.googleapis.com/css?family=Quando' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Droid+Sans:400,300|Droid+Serif:400,300' rel='stylesheet' type='text/css'>
  <script src="js/vendor/custom.modernizr.js"></script>
  <script>
      Modernizr.load({
          // test if browser understands media queries
          test: Modernizr.mq('only all'),
          // if not load ie8-grid
          nope: 'css/ie8-grid-foundation-4.css'
      });
  </script>
  <!--[if lt IE 9]>
  <link rel="stylesheet" href="css/ie-fixes.css">
  <![endif]-->
</head>

app/views/shared/_main_navigation.html.erb
  <div class="header">

<div class="row">
  <div class="columns large-12  header-logo"> <a href="index.html"> <%= image_tag("logo.png", alt:"") %></a> </div>
  <div class="columns large-12">





    <nav>
      <section>
        <ul class="sf-menu large-12">

          <li><%= link_to 'HOME', page_home_path %></li>
          <li><%= link_to 'ABOUT US' , page_about_path%></li>

          <li><%= link_to 'PROFILE' , page_profile_path%></li>

            <ul class="dropdown">
              <li class="has-dropdown"><a href="#">Dropdown Level 1a</a>
                <ul class="dropdown">
                  <li><a href="#">Dropdown Level 2a</a></li>
                  <li><a href="#">Dropdown Level 2b</a></li>
                </ul>
              </li>
              <li><a href="#">Dropdown Level 1b</a></li>
              <li><a href="#">Dropdown Level 1c</a></li>
              <li><a href="#">Dropdown Level 1d</a></li>
              <li><a href="#">See all &rarr;</a></li>
            </ul>
          </li>
          <li><%= link_to 'SERVICES' , page_services_path %></li>
          <li><%= link_to 'CONTACT US' , page_contact_path %></li>
          <li><%= link_to 'RIDES', page_rides_path %></li>
        </ul>
      </section>
    </nav>
  </div>
</div>
<div class="row">
  <div class="columns large-12 small-top-menu">
    <div class="row">
      <div class="columns large-12 plr0 top-nav">
        <form name="dropdown" class="dropdown" action="#">
          <nav>
            <section>
              <select name="selected" id="target" accesskey="E" onChange="goToNewPage(document.dropdown.selected)">
                <option value="index.html">home</option>
                <option value="about.html">about us</option>
                <option value="blog.html">blog</option>
                <option value="gallery.html">gallery</option>
                <option value="services.html">services</option>
                <option value="contact.html">contact us</option>
              </select>
            </section>
          </nav>
        </form>
      </div>
    </div>
  </div>

</div></div>